---
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Verify Docker is running
  command: docker info
  changed_when: false
  register: docker_info
  become: no

- name: Display Docker version
  command: docker --version
  changed_when: false
  register: docker_version
  become: no

- name: Show Docker version
  debug:
    msg: "Docker is ready: {{ docker_version.stdout }}"